// ===== 初一数学 上册数据（第一部分：第1-2章）=====
var mathDataUpPart1 = {
    title: "初一数学 · 上册",
    icon: "📖",
    description: "涵盖有理数、整式的加减、一元一次方程、几何图形初步四大章节",
    chapters: [
        // ===== 第一章 有理数 =====
        {
            title: "第一章 有理数",
            icon: "🔢",
            color: "#FF6B6B",
            lessons: [
                {
                    id: "1-1",
                    title: "1.1 正数和负数",
                    icon: "🌡️",
                    difficulty: "基础",
                    content: [
                        { type: "heading", text: "一、相反意义的量" },
                        { type: "paragraph", text: "在日常生活中，我们经常会遇到一些具有<strong>相反意义</strong>的量。比如：温度有零上和零下，海拔有高于海平面和低于海平面，财务有收入和支出，方向有向东和向西。" },
                        { type: "paragraph", text: "这些量有一个共同特点：它们都包含两个方向，且这两个方向的意义恰好相反。比如，当你存入100元和取出100元，这两个动作对余额的影响刚好是相反的——一个让余额增加，一个让余额减少。" },
                        { type: "paragraph", text: "在小学阶段，我们学习的数（自然数、分数、小数）已经不够用了。比如，如何用数来表示\"零下5度\"？如何表示\"欠款200元\"？为了区分这两种相反方向的量，数学家们引入了新的数——<strong>正数和负数</strong>。" },
                        { type: "svg", svg: '<svg viewBox="0 0 600 280" xmlns="http://www.w3.org/2000/svg"><rect x="120" y="30" width="40" height="200" rx="20" fill="#E3F2FD" stroke="#5B8DEF" stroke-width="2"/><rect x="130" y="120" width="20" height="110" rx="10" fill="#FF6B6B"/><circle cx="140" cy="240" r="25" fill="#FF6B6B"/><line x1="100" y1="60" x2="115" y2="60" stroke="#333" stroke-width="1.5"/><text x="80" y="65" font-size="14" fill="#333">10°</text><line x1="100" y1="100" x2="115" y2="100" stroke="#333" stroke-width="1.5"/><text x="80" y="105" font-size="14" fill="#333">5°</text><line x1="95" y1="130" x2="115" y2="130" stroke="#333" stroke-width="2"/><text x="70" y="135" font-size="14" fill="#333" font-weight="bold">0°</text><line x1="100" y1="160" x2="115" y2="160" stroke="#333" stroke-width="1.5"/><text x="75" y="165" font-size="14" fill="#2196F3">-5°</text><line x1="100" y1="200" x2="115" y2="200" stroke="#333" stroke-width="1.5"/><text x="75" y="205" font-size="14" fill="#2196F3">-10°</text><text x="115" y="25" font-size="13" fill="#666">温度计</text><line x1="300" y1="130" x2="560" y2="130" stroke="#5B8DEF" stroke-width="2" stroke-dasharray="5,3"/><text x="300" y="125" font-size="13" fill="#5B8DEF">海平面 (0m)</text><path d="M 350 130 L 400 50 L 450 130 Z" fill="#66BB6A" stroke="#43A047" stroke-width="1.5"/><text x="385" y="45" font-size="13" fill="#333">+8848m</text><text x="370" y="148" font-size="12" fill="#66BB6A">珠穆朗玛峰</text><path d="M 470 130 Q 500 200 530 130 Z" fill="#26A69A" stroke="#00897B" stroke-width="1.5"/><text x="495" y="215" font-size="13" fill="#333">-10909m</text><text x="475" y="148" font-size="12" fill="#26A69A">马里亚纳海沟</text></svg>', caption: "1-1 生活中具有相反意义的量：温度与海拔" },
                        { type: "svg", svg: '<svg viewBox="0 0 600 200" xmlns="http://www.w3.org/2000/svg"><text x="20" y="30" font-size="15" fill="#5B8DEF" font-weight="bold">生活中相反意义的量举例</text><rect x="20" y="50" width="130" height="60" rx="10" fill="#E8F5E9" stroke="#66BB6A" stroke-width="1.5"/><text x="85" y="75" text-anchor="middle" font-size="13" fill="#2E7D32" font-weight="bold">收入</text><text x="85" y="95" text-anchor="middle" font-size="12" fill="#555">+500元</text><rect x="160" y="50" width="130" height="60" rx="10" fill="#FFEBEE" stroke="#FF6B6B" stroke-width="1.5"/><text x="225" y="75" text-anchor="middle" font-size="13" fill="#C62828" font-weight="bold">支出</text><text x="225" y="95" text-anchor="middle" font-size="12" fill="#555">-300元</text><rect x="310" y="50" width="130" height="60" rx="10" fill="#E8F5E9" stroke="#66BB6A" stroke-width="1.5"/><text x="375" y="75" text-anchor="middle" font-size="13" fill="#2E7D32" font-weight="bold">上升</text><text x="375" y="95" text-anchor="middle" font-size="12" fill="#555">+50m</text><rect x="450" y="50" width="130" height="60" rx="10" fill="#FFEBEE" stroke="#FF6B6B" stroke-width="1.5"/><text x="515" y="75" text-anchor="middle" font-size="13" fill="#C62828" font-weight="bold">下降</text><text x="515" y="95" text-anchor="middle" font-size="12" fill="#555">-30m</text><rect x="95" y="130" width="130" height="60" rx="10" fill="#E8F5E9" stroke="#66BB6A" stroke-width="1.5"/><text x="160" y="155" text-anchor="middle" font-size="13" fill="#2E7D32" font-weight="bold">盈利</text><text x="160" y="175" text-anchor="middle" font-size="12" fill="#555">+2000元</text><rect x="375" y="130" width="130" height="60" rx="10" fill="#FFEBEE" stroke="#FF6B6B" stroke-width="1.5"/><text x="440" y="155" text-anchor="middle" font-size="13" fill="#C62828" font-weight="bold">亏损</text><text x="440" y="175" text-anchor="middle" font-size="12" fill="#555">-1500元</text></svg>', caption: "1-2 更多相反意义的量的例子" },
                        { type: "heading", text: "二、正数和负数的定义" },
                        { type: "keypoint", label: "重点", text: "<strong>正数</strong>：大于 0 的数叫做正数。如 $+5$、$3$、$\\frac{1}{2}$、$0.6$ 等都是正数。正数前面的 \"+\" 号可以省略不写。<br><strong>负数</strong>：在正数前面加上 \"-\" 号的数叫做负数。如 $-5$、$-3$、$-\\frac{1}{2}$、$-0.6$ 等都是负数。负数前面的 \"-\" 号不能省略。" },
                        { type: "paragraph", text: "简单来说，我们在小学学过的数（除了0）前面加上\"-\"号，就变成了负数。正数就是我们以前学的数（除了0），有时为了强调是正数，会在前面加\"+\"号，但通常省略不写。" },
                        { type: "warn", label: "易错点", text: "<strong>0 既不是正数，也不是负数！</strong>0 是正数和负数的分界。在实际问题中，0 往往表示\"没有\"或\"基准\"。例如：温度 $0\\degree C$ 不是\"没有温度\"，而是冰水混合物的温度，是一个确定的温度值。" },
                        { type: "tip", label: "深入理解", text: "为什么0不是正数也不是负数？因为正数表示比0大的数，负数表示比0小的数，而0本身既不比0大也不比0小。0是一个特殊的数，它连接了正数和负数，是数轴上的分界点。" },
                        { type: "heading", text: "三、用正负数表示相反意义的量" },
                        { type: "tip", label: "方法", text: "一般约定：<strong>向北、向东、上升、增加、收入、盈余</strong>等为正方向；<strong>向南、向西、下降、减少、支出、亏损</strong>等为负方向。但具体问题中，哪个为正可以自行规定，只要两个方向相反即可。" },
                        { type: "paragraph", text: "使用正负数表示相反意义的量时，关键是先确定哪个方向为正（通常选我们更关注或更有利的方向为正），然后相反方向就自动为负。比如：如果规定\"向南走\"为正方向，那么\"向北走\"就为负方向。" },
                        { type: "example", title: "例题1", question: "（1）如果收入 100 元记作 $+100$ 元，那么支出 50 元记作什么？<br>（2）如果向东走 30 米记作 $+30$ 米，那么向西走 20 米记作什么？", solution: "（1）支出与收入是相反意义的量，收入为正，所以支出 50 元记作 $-50$ 元。<br>（2）向西与向东是相反方向，向东为正，所以向西走 20 米记作 $-20$ 米。" },
                        { type: "example", title: "例题2", question: "某水库水位变化如下：第一天上升 $5cm$，第二天下降 $3cm$，第三天下降 $4cm$，第四天上升 $6cm$。如果上升为正，用正负数表示四天的水位变化，并求总变化量。", solution: "第一天：$+5cm$；第二天：$-3cm$；第三天：$-4cm$；第四天：$+6cm$。<br>总变化量 $= (+5) + (-3) + (-4) + (+6) = 5 - 3 - 4 + 6 = 4cm$<br>所以四天水位总共上升了 $4cm$。" },
                        { type: "example", title: "例题3", question: "某商品包装上标有\"$250 \\pm 5g$\"，请解释这个标注的含义，并说明合格产品的质量范围。", solution: "\"$250 \\pm 5g$\"表示该商品的标准质量为 $250g$，允许误差为 $\\pm 5g$。<br>即最多不超过 $250 + 5 = 255g$，最少不少于 $250 - 5 = 245g$。<br>合格产品质量范围为 $245g \\sim 255g$。" },
                        { type: "table", headers: ["实际情境", "规定为正", "规定为负", "举例"], rows: [
                            ["温度", "零上温度", "零下温度", "$+5\\degree C$，$-3\\degree C$"],
                            ["海拔", "高于海平面", "低于海平面", "$+200m$，$-50m$"],
                            ["收支", "收入", "支出", "$+500$ 元，$-300$ 元"],
                            ["方向", "向东/向北", "向西/向南", "$+30m$，$-20m$"],
                            ["经营", "盈利", "亏损", "$+2000$ 元，$-1500$ 元"],
                            ["股价", "上涨", "下跌", "$+2.5$，$-1.8$"]
                        ]},
                        { type: "heading", text: "四、知识拓展：负数的历史" },
                        { type: "paragraph", text: "负数的概念最早出现在中国古代。在《九章算术》（约公元1世纪）中，已经给出了正负数加减运算的法则，并用红色算筹表示正数，黑色算筹表示负数。这比欧洲数学家接受负数早了一千多年！" },
                        { type: "paragraph", text: "在印度，数学家婆罗摩笈多（Brahmagupta，公元598-665年）在公元628年也对负数进行了系统研究。而在欧洲，直到16世纪，很多数学家仍然不接受负数，认为\"比零小的数\"是不可理解的。直到笛卡尔（Descartes）创立坐标系后，负数才逐渐被广泛接受。" },
                        { type: "tip", label: "学习建议", text: "学习正数和负数时，最重要的是理解\"相反意义\"这个核心概念。遇到实际问题时，先想清楚哪两个量是相反的，再规定哪个为正、哪个为负，最后用正负数来表示。" }
                    ],
                    exercises: [
                        { type: "choice", question: "下列说法中，正确的是（　　）", options: ["0 是正数", "0 是负数", "0 既不是正数也不是负数", "0 既是正数也是负数"], answer: "C", explanation: "0 是正数和负数的分界线，它既不是正数，也不是负数。正数是大于 0 的数，负数是小于 0 的数，而 0 本身既不属于正数也不属于负数。" },
                        { type: "choice", question: "如果向东走 50 米记作 $+50$ 米，那么向西走 30 米记作（　　）", options: ["$+30$ 米", "$-30$ 米", "$+50$ 米", "$-50$ 米"], answer: "B", explanation: "因为向西与向东是相反方向，向东规定为正方向（$+50$ 米），所以向西走 30 米应记作 $-30$ 米。" },
                        { type: "choice", question: "下面关于\"$-8$\"的说法，正确的是（　　）", options: ["$-8$ 是一个负数，它的\"-\"号可以省略", "$-8$ 是一个负数，\"-\"号不能省略", "$-8$ 是一个正数", "$-8$ 既不是正数也不是负数"], answer: "B", explanation: "$-8$ 是负数，负数前面的\"-\"号是负数的标志，不能省略。正数前面的\"+\"号可以省略，但负数前面的\"-\"号不能省略。" },
                        { type: "fill", question: "某食品包装袋上标有\"净含量 $500\\pm5$g\"，这表示该食品的净含量最多不多于 ____ g，最少不少于 ____ g。", answer: "505,495", explanation: "\"$500\\pm5$g\"表示净含量可以在 500g 的基础上多 5g 或少 5g。最多为 $500+5=505$g，最少为 $500-5=495$g。" },
                        { type: "fill", question: "如果水位下降 $3cm$ 记作 $-3cm$，那么水位上升 $7cm$ 记作 ____ $cm$；如果某天水位变化记作 $0cm$，说明该天水位 ____。", answer: "+7,不变", explanation: "下降为负，则上升为正，上升 $7cm$ 记作 $+7cm$。水位变化为 $0cm$ 表示既没有上升也没有下降，水位不变。" }
                    ]
                },
                {
                    id: "1-2",
                    title: "1.2 有理数",
                    icon: "📊",
                    difficulty: "重要",
                    content: [
                        { type: "heading", text: "一、有理数的概念" },
                        { type: "paragraph", text: "在上一节课中，我们认识了正数和负数。现在我们要把这些数进行分类整理。为了更好地研究数的性质和运算规律，数学上引入了<strong>有理数</strong>的概念。" },
                        { type: "keypoint", label: "重点定义", text: "<strong>有理数</strong>：能够写成分数形式 $\\frac{p}{q}$（其中 $p$、$q$ 是整数，$q \\neq 0$）的数叫做有理数。<br>整数和分数统称为有理数。" },
                        { type: "paragraph", text: "简单来说，<strong>整数</strong>（如 $3$、$-5$、$0$）和<strong>分数</strong>（如 $\\frac{1}{2}$、$-\\frac{3}{4}$）统称为有理数。注意这里的\"分数\"是广义的，包括有限小数和无限循环小数，因为它们都可以化为分数形式。" },
                        { type: "heading", text: "二、有理数的分类" },
                        { type: "keypoint", label: "分类一（按定义）", text: "<strong>有理数</strong>分为：① <strong>整数</strong>：正整数、零、负整数；② <strong>分数</strong>：正分数、负分数" },
                        { type: "keypoint", label: "分类二（按正负）", text: "<strong>有理数</strong>分为：① <strong>正有理数</strong>：正整数、正分数；② <strong>零</strong>（$0$）；③ <strong>负有理数</strong>：负整数、负分数" },
                        { type: "svg", svg: '<svg viewBox="0 0 680 320" xmlns="http://www.w3.org/2000/svg"><rect x="270" y="10" width="140" height="40" rx="8" fill="#5B8DEF"/><text x="340" y="36" text-anchor="middle" font-size="16" fill="#fff" font-weight="bold">有理数</text><line x1="340" y1="50" x2="180" y2="90" stroke="#999" stroke-width="1.5"/><line x1="340" y1="50" x2="500" y2="90" stroke="#999" stroke-width="1.5"/><rect x="120" y="90" width="120" height="36" rx="8" fill="#FF8A65"/><text x="180" y="113" text-anchor="middle" font-size="15" fill="#fff" font-weight="bold">整数</text><rect x="440" y="90" width="120" height="36" rx="8" fill="#66BB6A"/><text x="500" y="113" text-anchor="middle" font-size="15" fill="#fff" font-weight="bold">分数</text><line x1="180" y1="126" x2="100" y2="165" stroke="#999" stroke-width="1.5"/><line x1="180" y1="126" x2="180" y2="165" stroke="#999" stroke-width="1.5"/><line x1="180" y1="126" x2="260" y2="165" stroke="#999" stroke-width="1.5"/><rect x="60" y="165" width="80" height="32" rx="6" fill="#FFE0B2" stroke="#FF8A65" stroke-width="1"/><text x="100" y="186" text-anchor="middle" font-size="13" fill="#E65100">正整数</text><rect x="140" y="165" width="80" height="32" rx="6" fill="#FFE0B2" stroke="#FF8A65" stroke-width="1"/><text x="180" y="186" text-anchor="middle" font-size="13" fill="#E65100">零(0)</text><rect x="220" y="165" width="80" height="32" rx="6" fill="#FFE0B2" stroke="#FF8A65" stroke-width="1"/><text x="260" y="186" text-anchor="middle" font-size="13" fill="#E65100">负整数</text><line x1="500" y1="126" x2="440" y2="165" stroke="#999" stroke-width="1.5"/><line x1="500" y1="126" x2="560" y2="165" stroke="#999" stroke-width="1.5"/><rect x="400" y="165" width="80" height="32" rx="6" fill="#C8E6C9" stroke="#66BB6A" stroke-width="1"/><text x="440" y="186" text-anchor="middle" font-size="13" fill="#1B5E20">正分数</text><rect x="520" y="165" width="80" height="32" rx="6" fill="#C8E6C9" stroke="#66BB6A" stroke-width="1"/><text x="560" y="186" text-anchor="middle" font-size="13" fill="#1B5E20">负分数</text><text x="100" y="215" text-anchor="middle" font-size="11" fill="#999">如: 1,2,3...</text><text x="180" y="215" text-anchor="middle" font-size="11" fill="#999">如: 0</text><text x="260" y="215" text-anchor="middle" font-size="11" fill="#999">如: -1,-2...</text><text x="440" y="215" text-anchor="middle" font-size="11" fill="#999">如: 1/2, 0.5</text><text x="560" y="215" text-anchor="middle" font-size="11" fill="#999">如: -1/3, -0.7</text><line x1="340" y1="50" x2="340" y2="250" stroke="#AB47BC" stroke-width="1" stroke-dasharray="3,3"/><text x="100" y="250" text-anchor="middle" font-size="12" fill="#AB47BC" font-weight="bold">正整数</text><text x="440" y="250" text-anchor="middle" font-size="12" fill="#AB47BC" font-weight="bold">正分数</text><rect x="60" y="265" width="200" height="30" rx="6" fill="#F3E5F5" stroke="#AB47BC" stroke-width="1"/><text x="160" y="285" text-anchor="middle" font-size="13" fill="#7B1FA2">正有理数</text><rect x="420" y="265" width="200" height="30" rx="6" fill="#F3E5F5" stroke="#AB47BC" stroke-width="1"/><text x="520" y="285" text-anchor="middle" font-size="13" fill="#7B1FA2">负有理数</text><text x="260" y="285" text-anchor="middle" font-size="13" fill="#7B1FA2" font-weight="bold">零</text></svg>', caption: "1-3 有理数的两种分类方法" },
                        { type: "tip", label: "注意", text: "有限小数（如 $0.5$）和无限循环小数（如 $0.\\dot{3}$）都可以化为分数形式，所以它们也是有理数。但<strong>无限不循环小数</strong>（如 $\\pi$）不能化为分数，不是有理数。" },
                        { type: "warn", label: "易错点", text: "① $\\pi$ 不是有理数！$\\pi = 3.14159...$ 是无限不循环小数，不能化为分数。<br>② $0$ 是整数，也是有理数，但既不是正数也不是负数。<br>③ 正数和正有理数不同——正数包含所有大于0的数（包括 $\\pi$ 等），而正有理数只包含能化为分数的正数。" },
                        { type: "example", title: "例题1", question: "将下列各数分别填入相应的集合中：<br>$-3$，$0$，$+5$，$-\\frac{1}{2}$，$0.7$，$-2.8$，$\\frac{4}{3}$，$-10$，$+100$<br>（1）正整数集合　（2）负整数集合　（3）正分数集合　（4）负分数集合", solution: "（1）正整数集合：$\\{+5, +100\\}$<br>（2）负整数集合：$\\{-3, -10\\}$<br>（3）正分数集合：$\\{0.7, \\frac{4}{3}\\}$（$0.7 = \\frac{7}{10}$）<br>（4）负分数集合：$\\{-\\frac{1}{2}, -2.8\\}$（$-2.8 = -\\frac{14}{5}$）<br>注意：$0$ 既不属于正数集合也不属于负数集合。" },
                        { type: "heading", text: "三、数轴" },
                        { type: "paragraph", text: "<strong>数轴</strong>是研究有理数的重要工具。它把\"数\"和\"形\"结合起来，让我们可以直观地看到数的大小关系和位置关系。" },
                        { type: "keypoint", label: "重点定义", text: "<strong>数轴</strong>：规定了原点、正方向和单位长度的直线叫做数轴。三要素：<strong>原点</strong>、<strong>正方向</strong>、<strong>单位长度</strong>。" },
                        { type: "svg", svg: '<svg viewBox="0 0 600 130" xmlns="http://www.w3.org/2000/svg"><line x1="40" y1="70" x2="560" y2="70" stroke="#333" stroke-width="2"/><polygon points="560,70 550,65 550,75" fill="#333"/><text x="565" y="75" font-size="14" fill="#333">+</text><circle cx="300" cy="70" r="4" fill="#333"/><text x="294" y="95" font-size="14" fill="#333" font-weight="bold">0</text><text x="270" y="55" font-size="12" fill="#5B8DEF">原点</text><g font-size="13" fill="#333"><line x1="100" y1="65" x2="100" y2="75" stroke="#333" stroke-width="1.5"/><text x="96" y="95">-4</text><line x1="180" y1="65" x2="180" y2="75" stroke="#333" stroke-width="1.5"/><text x="176" y="95">-1</text><line x1="340" y1="65" x2="340" y2="75" stroke="#333" stroke-width="1.5"/><text x="336" y="95">1</text><line x1="420" y1="65" x2="420" y2="75" stroke="#333" stroke-width="1.5"/><text x="416" y="95">3</text></g><text x="500" y="55" font-size="12" fill="#66BB6A">正方向 →</text><line x1="300" y1="115" x2="340" y2="115" stroke="#FF8A65" stroke-width="2"/><text x="305" y="128" font-size="12" fill="#FF8A65">单位长度</text></svg>', caption: "1-4 数轴及三要素" },
                        { type: "paragraph", text: "数轴上的每一个点都对应一个数，而且<strong>右边的点表示的数总比左边的点表示的数大</strong>。这意味着：正数在原点右边，负数在原点左边，正数大于0，负数小于0，正数大于一切负数。" },
                        { type: "tip", label: "画数轴的步骤", text: "① 画一条水平直线；② 在直线上任取一点作为原点，表示0；③ 确定正方向（通常向右），画上箭头；④ 选取适当的长度作为单位长度，从原点向右依次标出 $1, 2, 3, \\cdots$，向左依次标出 $-1, -2, -3, \\cdots$。" },
                        { type: "example", title: "例题2", question: "在数轴上表示下列各数，并按从小到大的顺序排列：<br>$-3$，$+2$，$0$，$-1.5$，$+3.5$", solution: "在数轴上从左到右依次标出：$-3$，$-1.5$，$0$，$+2$，$+3.5$。<br>从小到大排列：$-3 < -1.5 < 0 < +2 < +3.5$<br>（数轴上右边的数大于左边的数）" },
                        { type: "heading", text: "四、相反数" },
                        { type: "keypoint", label: "重点定义", text: "<strong>相反数</strong>：只有符号不同的两个数叫做互为相反数。特别地，$0$ 的相反数是 $0$。数 $a$ 的相反数是 $-a$。" },
                        { type: "svg", svg: '<svg viewBox="0 0 500 100" xmlns="http://www.w3.org/2000/svg"><line x1="30" y1="50" x2="470" y2="50" stroke="#333" stroke-width="2"/><polygon points="470,50 460,45 460,55" fill="#333"/><circle cx="250" cy="50" r="3" fill="#333"/><text x="246" y="72" font-size="13" fill="#333">0</text><circle cx="130" cy="50" r="5" fill="#FF6B6B"/><text x="124" y="35" font-size="14" fill="#FF6B6B" font-weight="bold">-3</text><circle cx="370" cy="50" r="5" fill="#66BB6A"/><text x="366" y="35" font-size="14" fill="#66BB6A" font-weight="bold">3</text><line x1="130" y1="50" x2="370" y2="50" stroke="#AB47BC" stroke-width="1.5" stroke-dasharray="4,3"/><text x="200" y="25" font-size="12" fill="#AB47BC">到原点距离相等</text></svg>', caption: "1-5 相反数在数轴上的表示" },
                        { type: "paragraph", text: "从数轴上看，互为相反数的两个点位于原点两侧，且到原点的距离相等。这也是\"相反数\"的几何意义。" },
                        { type: "tip", label: "性质", text: "① $a$ 的相反数是 $-a$，即 $-(-a) = a$<br>② 互为相反数的两个数之和为 $0$，即 $a + (-a) = 0$<br>③ <strong>相反数等于本身的数只有 $0$</strong><br>④ 在一个数前面添\"-\"号，就是求它的相反数" },
                        { type: "example", title: "例题3", question: "（1）求 $-7$ 的相反数；<br>（2）化简 $-(-(-5))$；<br>（3）已知 $a$ 和 $b$ 互为相反数，求 $a + b$ 的值。", solution: "（1）$-7$ 的相反数是 $-(-7) = 7$<br>（2）$-(-(-5)) = -5$（三重负号，奇数个为负）<br>（3）互为相反数的两个数之和为0，所以 $a + b = 0$" },
                        { type: "heading", text: "五、绝对值" },
                        { type: "paragraph", text: "<strong>绝对值</strong>是刻画一个数与原点距离的量。无论数在原点的左边还是右边，我们只关心它离原点有多远，这个\"距离\"就是绝对值。" },
                        { type: "keypoint", label: "重点定义", text: "<strong>绝对值</strong>：数轴上表示数 $a$ 的点与原点的距离叫做数 $a$ 的绝对值，记作 $|a|$。" },
                        { type: "formula", text: "$$|a| = \\begin{cases} a, & a > 0 \\\\ 0, & a = 0 \\\\ -a, & a < 0 \\end{cases}$$" },
                        { type: "paragraph", text: "<strong>正数的绝对值是它本身；负数的绝对值是它的相反数；0的绝对值是0。</strong>" },
                        { type: "svg", svg: '<svg viewBox="0 0 600 120" xmlns="http://www.w3.org/2000/svg"><line x1="30" y1="60" x2="570" y2="60" stroke="#333" stroke-width="2"/><polygon points="570,60 560,55 560,65" fill="#333"/><circle cx="300" cy="60" r="3" fill="#333"/><text x="296" y="80" font-size="12" fill="#333">0</text><circle cx="150" cy="60" r="5" fill="#FF6B6B"/><text x="144" y="45" font-size="13" fill="#FF6B6B" font-weight="bold">-4</text><circle cx="450" cy="60" r="5" fill="#66BB6A"/><text x="446" y="45" font-size="13" fill="#66BB6A" font-weight="bold">4</text><rect x="150" y="55" width="150" height="10" fill="#FF6B6B" opacity="0.3"/><rect x="300" y="55" width="150" height="10" fill="#66BB6A" opacity="0.3"/><text x="190" y="100" font-size="12" fill="#FF6B6B">距离=4 →</text><text x="330" y="100" font-size="12" fill="#66BB6A">← 距离=4</text><text x="250" y="30" text-anchor="middle" font-size="14" fill="#AB47BC" font-weight="bold">|-4| = |4| = 4</text></svg>', caption: "1-6 绝对值的几何意义：到原点的距离" },
                        { type: "example", title: "例题4", question: "求下列各数的绝对值：$|5|$，$|-7|$，$|0|$，$\\left|-\\frac{3}{4}\\right|$。", solution: "$|5| = 5$（正数的绝对值是它本身）；<br>$|-7| = 7$（负数的绝对值是它的相反数）；<br>$|0| = 0$；<br>$\\left|-\\frac{3}{4}\\right| = \\frac{3}{4}$（负数的绝对值是它的相反数）。" },
                        { type: "example", title: "例题5", question: "已知 $|a| = 3$，$|b| = 5$，且 $a > 0$，$b < 0$，求 $a$ 和 $b$ 的值。", solution: "由 $|a| = 3$ 得 $a = 3$ 或 $a = -3$，又 $a > 0$，所以 $a = 3$；<br>由 $|b| = 5$ 得 $b = 5$ 或 $b = -5$，又 $b < 0$，所以 $b = -5$。" },
                        { type: "tip", label: "性质", text: "① 绝对值是非负数，即 $|a| \\geq 0$<br>② 绝对值等于本身的数是<strong>正数和0</strong><br>③ $|a| = |-a|$<br>④ 绝对值等于0的数只有 $0$<br>⑤ 互为相反数的两个数的绝对值相等" },
                        { type: "keypoint", label: "有理数大小比较", text: "① 正数 $> 0 >$ 负数；<br>② 两个正数，绝对值大的数大；<br>③ <strong>两个负数，绝对值大的数反而小</strong>！如 $-3 < -2$，因为 $|-3| = 3 > |-2| = 2$。" },
                        { type: "example", title: "例题6", question: "比较下列各组数的大小：<br>（1）$-5$ 和 $-3$　（2）$-\\frac{1}{2}$ 和 $-\\frac{1}{3}$　（3）$-(-2)$ 和 $-|-3|$", solution: "（1）$|-5| = 5 > |-3| = 3$，所以 $-5 < -3$<br>（2）$|-\\frac{1}{2}| = \\frac{1}{2} > |-\\frac{1}{3}| = \\frac{1}{3}$，所以 $-\\frac{1}{2} < -\\frac{1}{3}$<br>（3）$-(-2) = 2$，$-|-3| = -3$，$2 > -3$，所以 $-(-2) > -|-3|$" },
                        { type: "heading", text: "六、知识拓展" },
                        { type: "paragraph", text: "数轴是法国数学家笛卡尔（René Descartes）在17世纪发明的坐标系的基础。数轴可以看作是一维的坐标系，而平面直角坐标系就是两条数轴的组合。数轴将\"数\"和\"形\"完美结合，是数学中\"数形结合\"思想的重要体现。" }
                    ],
                    exercises: [
                        { type: "choice", question: "下列说法正确的是（　　）", options: ["有理数包括正有理数和负有理数", "0 不是有理数", "有理数包括整数和分数", "$-3$ 是分数"], answer: "C", explanation: "有理数包括正有理数、0和负有理数（A错误，漏了0）；0是有理数（B错误）；整数和分数统称有理数（C正确）；$-3$是整数不是分数（D错误）。" },
                        { type: "choice", question: "$-5$ 的相反数和绝对值分别是（　　）", options: ["$5$，$-5$", "$-5$，$5$", "$5$，$5$", "$-5$，$-5$"], answer: "C", explanation: "$-5$的相反数是$-(-5)=5$；$|-5|=5$（负数的绝对值等于它的相反数）。所以两者都是5。" },
                        { type: "choice", question: "下列各数中，最小的数是（　　）", options: ["$-1$", "$-3$", "$0$", "$-\\frac{1}{2}$"], answer: "B", explanation: "负数中绝对值越大的数越小。$|-3|=3$最大，所以$-3$是最小的数。也可画数轴：$-3 < -1 < -\\frac{1}{2} < 0$。" },
                        { type: "fill", question: "已知 $|a| = 3$，$|b| = 5$，且 $a > 0$，$b < 0$，则 $a = $ ____，$b = $ ____。", answer: "3,-5", explanation: "由$|a|=3$得$a=3$或$a=-3$，又$a>0$，所以$a=3$；由$|b|=5$得$b=5$或$b=-5$，又$b<0$，所以$b=-5$。" },
                        { type: "fill", question: "化简：$-(-(-6)) = $ ____；$-|{-8}| = $ ____。", answer: "-6,-8", explanation: "$-(-(-6))$：三重负号，奇数个负号为负，所以$= -6$。$-|-8| = -(8) = -8$（先求绝对值$|-8|=8$，再取相反数$-8$）。" }
                    ]
                },
                {
                    id: "1-3",
                    title: "1.3 有理数的加减法",
                    icon: "➕",
                    difficulty: "重点",
                    content: [
                        { type: "heading", text: "一、有理数的加法法则" },
                        { type: "paragraph", text: "有理数的加法是整个有理数运算的基础。与小学的加法不同，有理数的加法不仅要计算绝对值，还要确定结果的符号。我们分三种情况来学习。" },
                        { type: "keypoint", label: "重点法则", text: "① <strong>同号两数相加</strong>：取相同的符号，并把绝对值相加。如 $(-3)+(-5)=-(3+5)=-8$<br>② <strong>异号两数相加</strong>：取绝对值较大的加数的符号，并用较大的绝对值减去较小的绝对值。如 $(-7)+(+3)=-(7-3)=-4$<br>③ <strong>一个数同0相加</strong>：仍得这个数" },
                        { type: "paragraph", text: "理解加法法则的关键：先看两个数的符号是相同还是不同，这决定了结果的符号；再决定绝对值是相加还是相减。" },
                        { type: "svg", svg: '<svg viewBox="0 0 600 200" xmlns="http://www.w3.org/2000/svg"><text x="20" y="30" font-size="14" fill="#FF6B6B" font-weight="bold">同号相加：(-3) + (-5) = -8</text><line x1="40" y1="70" x2="560" y2="70" stroke="#333" stroke-width="2"/><polygon points="560,70 550,65 550,75" fill="#333"/><circle cx="300" cy="70" r="3" fill="#333"/><text x="296" y="90" font-size="12" fill="#333">0</text><circle cx="180" cy="70" r="5" fill="#FF6B6B"/><text x="174" y="60" font-size="13" fill="#FF6B6B" font-weight="bold">-3</text><circle cx="220" cy="70" r="5" fill="#FF6B6B"/><text x="214" y="60" font-size="13" fill="#FF6B6B" font-weight="bold">-5</text><circle cx="140" cy="70" r="6" fill="#D32F2F"/><text x="132" y="60" font-size="14" fill="#D32F2F" font-weight="bold">-8</text><text x="20" y="155" font-size="14" fill="#5B8DEF" font-weight="bold">异号相加：(-7) + (+3) = -4</text><line x1="40" y1="185" x2="560" y2="185" stroke="#333" stroke-width="2"/><polygon points="560,185 550,180 550,190" fill="#333"/><circle cx="300" cy="185" r="3" fill="#333"/><text x="296" y="178" font-size="11" fill="#333">0</text><circle cx="165" cy="185" r="5" fill="#FF6B6B"/><text x="158" y="178" font-size="12" fill="#FF6B6B" font-weight="bold">-7</text><circle cx="345" cy="185" r="5" fill="#66BB6A"/><text x="340" y="178" font-size="12" fill="#66BB6A" font-weight="bold">3</text><circle cx="220" cy="185" r="6" fill="#5B8DEF"/><text x="214" y="178" font-size="12" fill="#5B8DEF" font-weight="bold">-4</text></svg>', caption: "1-7 有理数加法在数轴上的表示" },
                        { type: "example", title: "例题1", question: "计算：$(1)$ $(-8)+(-12)$　$(2)$ $(-5)+(+9)$　$(3)$ $(-6)+(+6)$", solution: "$(1)$ 同号相加取负号：$-(8+12)=-20$<br>$(2)$ 异号，$9>5$取正号：$+(9-5)=+4=4$<br>$(3)$ 互为相反数相加得$0$" },
                        { type: "example", title: "例题2", question: "某天早上气温为 $-3\\degree C$，中午升高了 $5\\degree C$，晚上又降低了 $7\\degree C$，求晚上的气温。", solution: "晚上气温 $= -3 + 5 + (-7) = (-3+5) + (-7) = 2 + (-7) = -5\\degree C$<br>所以晚上的气温是 $-5\\degree C$。" },
                        { type: "tip", label: "特殊情况", text: "① 互为相反数的两个数相加，结果为 $0$：$a + (-a) = 0$<br>② 一个数与 $0$ 相加，仍得这个数：$a + 0 = a$<br>③ 两个正数相加，结果为正；两个负数相加，结果为负" },
                        { type: "heading", text: "二、加法运算律" },
                        { type: "keypoint", label: "运算律", text: "① <strong>加法交换律</strong>：$a + b = b + a$（两个数相加，交换加数的位置，和不变）<br>② <strong>加法结合律</strong>：$(a + b) + c = a + (b + c)$（三个数相加，先把前两个数相加，或者先把后两个数相加，和不变）" },
                        { type: "tip", label: "巧算技巧", text: "利用运算律进行巧算：① 把正数和正数相加、负数和负数相加；② 把互为相反数的数先相加（凑0）；③ 把凑整的数先相加（如 $2.5 + 7.5 = 10$）；④ 把同分母的分数先相加。" },
                        { type: "example", title: "例题3", question: "巧算：$(-23)+(+58)+(-17)+(+42)$", solution: "正数结合，负数结合：<br>$(-23)+(-17)+(+58)+(+42)$<br>$= -40 + 100 = 60$" },
                        { type: "example", title: "例题4", question: "巧算：$(+3.5)+(-2.7)+(-3.5)+(+0.7)$", solution: "凑0法：$(+3.5)+(-3.5) = 0$，剩下 $(-2.7)+(+0.7) = -2$<br>所以原式 $= 0 + (-2) = -2$" },
                        { type: "heading", text: "三、有理数的减法法则" },
                        { type: "paragraph", text: "有了加法法则，我们就可以把减法转化为加法来做。有理数减法的核心思想是：<strong>将减法转化为加法</strong>。" },
                        { type: "keypoint", label: "重点法则", text: "<strong>减法法则</strong>：减去一个数，等于加上这个数的相反数。$$a - b = a + (-b)$$" },
                        { type: "paragraph", text: "这个法则的意思是：要把减法变成加法，只需要把减号变成加号，同时把减数变成它的相反数。注意：被减数不变，只改变减号和减数。" },
                        { type: "svg", svg: '<svg viewBox="0 0 600 100" xmlns="http://www.w3.org/2000/svg"><rect x="20" y="20" width="250" height="60" rx="12" fill="#FFEBEE" stroke="#FF6B6B" stroke-width="2"/><text x="145" y="45" text-anchor="middle" font-size="18" fill="#C62828" font-weight="bold">a - b</text><text x="145" y="68" text-anchor="middle" font-size="12" fill="#666">减法</text><text x="290" y="55" font-size="24" fill="#5B8DEF">→</text><rect x="330" y="20" width="250" height="60" rx="12" fill="#E8F5E9" stroke="#66BB6A" stroke-width="2"/><text x="455" y="45" text-anchor="middle" font-size="18" fill="#2E7D32" font-weight="bold">a + (-b)</text><text x="455" y="68" text-anchor="middle" font-size="12" fill="#666">加法（减号变加号，减数变相反数）</text></svg>', caption: "1-8 减法转化为加法的过程" },
                        { type: "example", title: "例题5", question: "计算：$(1)$ $(-3)-(-5)$　$(2)$ $7-(-2)$　$(3)$ $0-(-8)$　$(4)$ $(-4)-(+6)$", solution: "$(1)$ $(-3)-(-5) = (-3)+(+5) = 2$<br>$(2)$ $7-(-2) = 7+(+2) = 9$<br>$(3)$ $0-(-8) = 0+(+8) = 8$<br>$(4)$ $(-4)-(+6) = (-4)+(-6) = -10$" },
                        { type: "warn", label: "易错点", text: "减法变加法时，<strong>两处要同时变</strong>：① 减号变加号；② 减数变相反数。只变一处是常见错误！<br>如 $3 - (-5)$：减号变加号，$-5$ 变 $+5$，得 $3 + 5 = 8$。不能只变一处。" },
                        { type: "heading", text: "四、加减混合运算" },
                        { type: "paragraph", text: "在有理数的加减混合运算中，我们需要把所有的减法都转化为加法，然后利用加法运算律进行简化计算。" },
                        { type: "list", items: ["第一步：将<strong>减法统一转化为加法</strong>，如 $a-b+c = a+(-b)+c$", "第二步：将加法写成<strong>省略加号的和</strong>形式，如 $a+(-b)+c = a-b+c$（这里的\"-\"号表示负数，不是减号）", "第三步：利用运算律进行<strong>巧算</strong>——同号结合、凑整、凑零"]},
                        { type: "example", title: "例题6", question: "计算：$(-12)-(-5)+(-8)-(+3)+(-7)$", solution: "转化为加法：$(-12)+(+5)+(-8)+(-3)+(-7)$<br>省略加号：$-12+5-8-3-7$<br>同号结合：$(-12-8-3-7)+5 = -30+5 = -25$" },
                        { type: "example", title: "例题7", question: "计算：$(-3.7)+(+2.5)-(-6.3)+(-2.5)$", solution: "转化为加法：$(-3.7)+(+2.5)+(+6.3)+(-2.5)$<br>凑零：$(+2.5)+(-2.5) = 0$<br>凑整：$(-3.7)+(+6.3) = 2.6$<br>原式 $= 0 + 2.6 = 2.6$" },
                        { type: "heading", text: "五、知识拓展" },
                        { type: "paragraph", text: "有理数的加减法在生活中的应用非常广泛。比如：银行账户的存取款记录、气温变化、股票涨跌、海拔变化等。掌握好有理数的加减法，就等于掌握了处理\"正反方向变化\"问题的数学工具。" },
                        { type: "tip", label: "学习方法", text: "初学有理数加减法时，建议：<br>① 先判断是同号还是异号；② 再确定结果的符号；③ 最后计算绝对值的加或减。<br>熟练之后，可以一步到位直接写出结果。" }
                    ],
                    exercises: [
                        { type: "choice", question: "计算 $(-7) + (+3)$ 的结果是（　　）", options: ["$-10$", "$-4$", "$4$", "$10$"], answer: "B", explanation: "异号两数相加，取绝对值较大的加数的符号。$|-7|=7$，$|+3|=3$，$7>3$取负号，$-(7-3)=-4$。" },
                        { type: "choice", question: "计算 $(-5) - (-8)$ 的结果是（　　）", options: ["$-13$", "$-3$", "$3$", "$13$"], answer: "C", explanation: "减去一个数等于加上它的相反数。$(-5)-(-8)=(-5)+(+8)$，异号相加，$8>5$取正号，$8-5=3$。" },
                        { type: "choice", question: "下列运算中，结果为正数的是（　　）", options: ["$(-3) + (-5)$", "$(-3) - (-5)$", "$0 + (-7)$", "$(-8) - (+2)$"], answer: "B", explanation: "A：同号负数相加，结果为负；B：$(-3)-(-5)=(-3)+5=2>0$，正确；C：$0+(-7)=-7<0$；D：$(-8)-2=-10<0$。" },
                        { type: "fill", question: "计算：$(-15)+(+7)-(-12)+(-4) = $ ____", answer: "0", explanation: "将减法转化为加法：$(-15)+(+7)+(+12)+(-4)$。同号结合：$(-15-4)+(7+12)=-19+19=0$。" },
                        { type: "fill", question: "某地一天中气温变化：早 $6$ 时 $-2\\degree C$，中午上升 $8\\degree C$，下午下降 $5\\degree C$，夜间又下降 $6\\degree C$，则该地夜间气温为 ____ $\\degree C$。", answer: "-5", explanation: "$-2+8+(-5)+(-6) = (-2-5-6)+8 = -13+8 = -5\\degree C$。" }
                    ]
                },
                {
                    id: "1-4",
                    title: "1.4 有理数的乘除法",
                    icon: "✖️",
                    difficulty: "重点",
                    content: [
                        { type: "heading", text: "一、有理数的乘法法则" },
                        { type: "paragraph", text: "有理数的乘法和小学学过的乘法类似，最大的区别是要确定积的符号。有理数乘法的核心口诀是：<strong>同号得正，异号得负</strong>。" },
                        { type: "keypoint", label: "重点法则", text: "<strong>两数相乘，同号得正，异号得负</strong>，并把绝对值相乘。任何数与 $0$ 相乘，都得 $0$。" },
                        { type: "svg", svg: '<svg viewBox="0 0 600 130" xmlns="http://www.w3.org/2000/svg"><rect x="20" y="10" width="560" height="110" rx="12" fill="#FAFBFC" stroke="#E0E0E0"/><text x="40" y="40" font-size="15" fill="#333" font-weight="bold">符号判断口诀</text><circle cx="80" cy="75" r="20" fill="#66BB6A"/><text x="80" y="81" text-anchor="middle" font-size="16" fill="#fff" font-weight="bold">+</text><text x="110" y="70" font-size="18" fill="#333">×</text><circle cx="140" cy="75" r="20" fill="#66BB6A"/><text x="140" y="81" text-anchor="middle" font-size="16" fill="#fff" font-weight="bold">+</text><text x="170" y="70" font-size="18" fill="#333">=</text><circle cx="200" cy="75" r="20" fill="#66BB6A"/><text x="200" y="81" text-anchor="middle" font-size="16" fill="#fff" font-weight="bold">+</text><text x="160" y="110" font-size="13" fill="#66BB6A" font-weight="bold">同号得正</text><circle cx="290" cy="75" r="20" fill="#FF6B6B"/><text x="290" y="81" text-anchor="middle" font-size="16" fill="#fff" font-weight="bold">−</text><text x="320" y="70" font-size="18" fill="#333">×</text><circle cx="350" cy="75" r="20" fill="#66BB6A"/><text x="350" y="81" text-anchor="middle" font-size="16" fill="#fff" font-weight="bold">+</text><text x="380" y="70" font-size="18" fill="#333">=</text><circle cx="410" cy="75" r="20" fill="#FF6B6B"/><text x="410" y="81" text-anchor="middle" font-size="16" fill="#fff" font-weight="bold">−</text><text x="370" y="110" font-size="13" fill="#FF6B6B" font-weight="bold">异号得负</text><text x="490" y="80" font-size="13" fill="#666">×0 = 0</text></svg>', caption: "1-9 乘法符号判断规则" },
                        { type: "example", title: "例题1", question: "计算：$(1)$ $(-4)\\times(-5)$　$(2)$ $(-6)\\times(+3)$　$(3)$ $(-7)\\times0$　$(4)$ $\\frac{2}{3}\\times(-\\frac{3}{4})$", solution: "$(1)$ 同号得正，$4\\times5=20$<br>$(2)$ 异号得负，$6\\times3=18$，结果$-18$<br>$(3)$ 任何数与0相乘得0<br>$(4)$ 异号得负，$\\frac{2}{3}\\times\\frac{3}{4}=\\frac{1}{2}$，结果$-\\frac{1}{2}$" },
                        { type: "paragraph", text: "<strong>多个有理数相乘</strong>时，积的符号由负因数的个数决定：负因数有<strong>偶数</strong>个时积为<strong>正</strong>；负因数有<strong>奇数</strong>个时积为<strong>负</strong>。只要有一个因数为 $0$，积就为 $0$。" },
                        { type: "tip", label: "口诀", text: "多个数相乘的符号判断：<strong>奇负偶正</strong>——负因数个数是奇数时积为负，是偶数时积为正。先看有没有0，有0积为0；没有0再数负号个数。" },
                        { type: "example", title: "例题2", question: "计算：$(-2)\\times(-3)\\times(-4)\\times(-5)$", solution: "有4个负因数（偶数个），积为正。<br>$2\\times3\\times4\\times5 = 120$<br>所以结果为 $+120$" },
                        { type: "example", title: "例题3", question: "计算：$(-1)\\times(-2)\\times(-3)\\times0\\times(-4)$", solution: "有一个因数为 $0$，所以积直接为 $0$。" },
                        { type: "heading", text: "二、乘法运算律" },
                        { type: "keypoint", label: "运算律", text: "① <strong>交换律</strong>：$a \\times b = b \\times a$<br>② <strong>结合律</strong>：$(a \\times b) \\times c = a \\times (b \\times c)$<br>③ <strong>分配律</strong>：$a \\times (b + c) = a \\times b + a \\times c$" },
                        { type: "tip", label: "巧算技巧", text: "① 把能凑整的数结合在一起（如 $2.5\\times4=10$）；② 把互为倒数的数结合（如 $\\frac{1}{3}\\times3=1$）；③ 乘法分配律可以简化带括号的计算；④ 逆向使用分配律可以合并同类项。" },
                        { type: "example", title: "例题4", question: "巧算：$(-\\frac{3}{4})\\times(-8)\\times(-\\frac{1}{3})$", solution: "利用交换律和结合律，把 $(-\\frac{3}{4})\\times(-\\frac{1}{3})$ 先算：<br>$(-\\frac{3}{4})\\times(-\\frac{1}{3}) = \\frac{1}{4}$<br>$\\frac{1}{4}\\times(-8) = -2$" },
                        { type: "example", title: "例题5", question: "巧算：$(-\\frac{1}{4})\\times(+8)\\times(-\\frac{5}{2})\\times(-1)$", solution: "三个负因数（奇数个），积为负。<br>$\\frac{1}{4}\\times8\\times\\frac{5}{2}\\times1 = \\frac{1\\times8\\times5\\times1}{4\\times2} = 5$<br>结果为 $-5$" },
                        { type: "heading", text: "三、有理数的除法法则" },
                        { type: "keypoint", label: "重点法则", text: "<strong>法则一</strong>：除以一个不等于 $0$ 的数，等于乘这个数的倒数。$a \\div b = a \\times \\frac{1}{b}$ ($b \\neq 0$)<br><strong>法则二</strong>：两数相除，<strong>同号得正，异号得负</strong>，并把绝对值相除。$0$ 除以任何非零数都得 $0$。" },
                        { type: "warn", label: "注意", text: "① $0$ 不能作除数！因为找不到一个数与 $0$ 相乘等于非零数。<br>② <strong>倒数</strong>：乘积为 $1$ 的两个数互为倒数。如 $-3$ 的倒数是 $-\\frac{1}{3}$。$0$ 没有倒数。<br>③ 正数的倒数是正数，负数的倒数是负数。" },
                        { type: "svg", svg: '<svg viewBox="0 0 600 120" xmlns="http://www.w3.org/2000/svg"><rect x="20" y="10" width="560" height="100" rx="12" fill="#F3E5F5" stroke="#AB47BC" stroke-width="1.5"/><text x="40" y="40" font-size="14" fill="#7B1FA2" font-weight="bold">求倒数的方法：</text><text x="40" y="65" font-size="13" fill="#333">正整数 $n$ 的倒数 → $\\frac{1}{n}$</text><text x="40" y="85" font-size="13" fill="#333">分数 $\\frac{a}{b}$ 的倒数 → $\\frac{b}{a}$（分子分母颠倒）</text><text x="300" y="65" font-size="13" fill="#333">小数 → 先化分数 → 再求倒数</text><text x="300" y="85" font-size="13" fill="#333">带分数 → 先化假分数 → 再求倒数</text><text x="40" y="105" font-size="12" fill="#FF6B6B">注意：0 没有倒数！</text></svg>', caption: "1-10 求各种数的倒数" },
                        { type: "example", title: "例题6", question: "计算：$(1)$ $(-18)\\div(-6)$　$(2)$ $(-\\frac{3}{4})\\div(+\\frac{3}{8})$　$(3)$ $0\\div(-5)$", solution: "$(1)$ 同号得正，$18\\div6=3$<br>$(2)$ 异号得负，$\\frac{3}{4}\\div\\frac{3}{8}=\\frac{3}{4}\\times\\frac{8}{3}=2$，结果$-2$<br>$(3)$ $0$除以任何非零数都得$0$" },
                        { type: "example", title: "例题7", question: "求下列各数的倒数：$(1)$ $-5$　$(2)$ $\\frac{3}{7}$　$(3)$ $-0.25$　$(4)$ $2\\frac{1}{3}$", solution: "$(1)$ $-5$ 的倒数是 $-\\frac{1}{5}$<br>$(2)$ $\\frac{3}{7}$ 的倒数是 $\\frac{7}{3}$<br>$(3)$ $-0.25 = -\\frac{1}{4}$，倒数是 $-4$<br>$(4)$ $2\\frac{1}{3} = \\frac{7}{3}$，倒数是 $\\frac{3}{7}$" },
                        { type: "heading", text: "四、四则混合运算" },
                        { type: "keypoint", label: "运算顺序", text: "① 先算<strong>乘方</strong>，再算<strong>乘除</strong>，最后算<strong>加减</strong>；② 有<strong>括号</strong>的先算括号里面的（小括号→中括号→大括号）；③ 同级运算从<strong>左到右</strong>依次进行。" },
                        { type: "example", title: "例题8", question: "计算：$(-3)\\times(-4)+(-12)\\div(+6)$", solution: "先乘除：$(-3)\\times(-4)=12$（同号得正）；$(-12)\\div(+6)=-2$（异号得负）<br>再加减：$12+(-2)=10$" },
                        { type: "example", title: "例题9", question: "计算：$[(-2)^3+(-3)^2]\\times(-\\frac{1}{2})$", solution: "先算乘方：$(-2)^3=-8$，$(-3)^2=9$<br>再算括号内：$(-8)+9=1$<br>最后乘法：$1\\times(-\\frac{1}{2})=-\\frac{1}{2}$" },
                        { type: "tip", label: "学习建议", text: "做混合运算时要：① 看清运算顺序；② 每一步都注意符号；③ 能巧算的尽量巧算（用运算律）；④ 养成检查的习惯，可以逆运算验证。" }
                    ],
                    exercises: [
                        { type: "choice", question: "计算 $(-6) \\times (-7)$ 的结果是（　　）", options: ["$-42$", "$-13$", "$13$", "$42$"], answer: "D", explanation: "两数相乘，同号得正（两个负数），绝对值相乘 $6\\times7=42$，结果为 $42$。" },
                        { type: "choice", question: "计算 $(-\\frac{1}{3}) \\div \\frac{2}{3}$ 的结果是（　　）", options: ["$-\\frac{2}{9}$", "$-\\frac{1}{2}$", "$\\frac{1}{2}$", "$\\frac{2}{9}$"], answer: "B", explanation: "除以一个数等于乘它的倒数。$(-\\frac{1}{3})\\times\\frac{3}{2}=-\\frac{3}{6}=-\\frac{1}{2}$。" },
                        { type: "choice", question: "$-2$ 的倒数是（　　）", options: ["$2$", "$-2$", "$\\frac{1}{2}$", "$-\\frac{1}{2}$"], answer: "D", explanation: "乘积为1的两个数互为倒数。$(-2)\\times(-\\frac{1}{2})=1$，所以$-2$的倒数是$-\\frac{1}{2}$。负数的倒数仍是负数。" },
                        { type: "fill", question: "计算：$(-2)^3 \\times (-3) + (-12) \\div (-4) = $ ____", answer: "27", explanation: "先乘方：$(-2)^3=-8$。再乘除：$(-8)\\times(-3)=24$（同号得正），$(-12)\\div(-4)=3$（同号得正）。最后加法：$24+3=27$。" },
                        { type: "fill", question: "计算：$(-\\frac{3}{4}) \\times (-\\frac{2}{3}) \\times (-\\frac{4}{5}) = $ ____", answer: "-2/5", explanation: "三个负因数（奇数个），积为负。$\\frac{3}{4}\\times\\frac{2}{3}\\times\\frac{4}{5}=\\frac{3\\times2\\times4}{4\\times3\\times5}=\\frac{24}{60}=\\frac{2}{5}$，结果为$-\\frac{2}{5}$。" }
                    ]
                },
                {
                    id: "1-5",
                    title: "1.5 有理数的乘方",
                    icon: "🔢",
                    difficulty: "重点",
                    content: [
                        { type: "heading", text: "一、乘方的概念" },
                        { type: "paragraph", text: "在数学中，我们经常遇到求几个相同因数的积的运算。比如边长为 $a$ 的正方形的面积是 $a \\times a$，棱长为 $a$ 的正方体的体积是 $a \\times a \\times a$。为了简便，数学家发明了<strong>乘方</strong>这种记法。" },
                        { type: "keypoint", label: "重点定义", text: "<strong>乘方</strong>：求 $n$ 个相同因数 $a$ 的积的运算叫做乘方，记作 $a^n$。$a$ 叫<strong>底数</strong>，$n$ 叫<strong>指数</strong>，$a^n$ 叫<strong>幂</strong>。<br>$$a^n = \\underbrace{a \\times a \\times \\cdots \\times a}_{n\\text{个}a}$$" },
                        { type: "svg", svg: '<svg viewBox="0 0 400 110" xmlns="http://www.w3.org/2000/svg"><text x="150" y="60" font-size="44" fill="#5B8DEF" font-weight="bold">a</text><text x="188" y="34" font-size="30" fill="#FF8A65" font-weight="bold">n</text><line x1="165" y1="70" x2="165" y2="88" stroke="#5B8DEF" stroke-width="1.5"/><text x="120" y="103" font-size="13" fill="#5B8DEF" font-weight="bold">底数</text><line x1="193" y1="30" x2="215" y2="15" stroke="#FF8A65" stroke-width="1.5"/><text x="220" y="13" font-size="13" fill="#FF8A65" font-weight="bold">指数</text><text x="260" y="55" font-size="15" fill="#666">= a × a × ... × a</text><text x="260" y="80" font-size="13" fill="#999">（n个a相乘）</text></svg>', caption: "1-11 乘方的结构" },
                        { type: "paragraph", text: "读法：$a^n$ 读作\"$a$ 的 $n$ 次方\"或\"$a$ 的 $n$ 次幂\"。例如 $2^3$ 读作\"2 的 3 次方\"，表示 $2\\times2\\times2=8$。" },
                        { type: "warn", label: "易错点", text: "<strong>$(-2)^4$ 与 $-2^4$ 的区别！</strong><br>$(-2)^4 = (-2)\\times(-2)\\times(-2)\\times(-2) = 16$（底数是 $-2$，4个$-2$相乘）<br>$-2^4 = -(2^4) = -(2\\times2\\times2\\times2) = -16$（底数是 $2$，前面的负号是整体取反）<br>关键区别：括号决定了底数是否包含负号！" },
                        { type: "svg", svg: '<svg viewBox="0 0 600 130" xmlns="http://www.w3.org/2000/svg"><rect x="20" y="10" width="270" height="110" rx="10" fill="#E8F5E9" stroke="#66BB6A" stroke-width="2"/><text x="155" y="40" text-anchor="middle" font-size="20" fill="#2E7D32" font-weight="bold">(-2)⁴ = 16</text><text x="155" y="65" text-anchor="middle" font-size="12" fill="#555">底数是 -2</text><text x="155" y="85" text-anchor="middle" font-size="12" fill="#555">(-2)×(-2)×(-2)×(-2)</text><text x="155" y="105" text-anchor="middle" font-size="12" fill="#66BB6A" font-weight="bold">偶次幂→正数</text><rect x="310" y="10" width="270" height="110" rx="10" fill="#FFEBEE" stroke="#FF6B6B" stroke-width="2"/><text x="445" y="40" text-anchor="middle" font-size="20" fill="#C62828" font-weight="bold">-2⁴ = -16</text><text x="445" y="65" text-anchor="middle" font-size="12" fill="#555">底数是 2</text><text x="445" y="85" text-anchor="middle" font-size="12" fill="#555">-(2×2×2×2)</text><text x="445" y="105" text-anchor="middle" font-size="12" fill="#FF6B6B" font-weight="bold">负号在外→取反</text></svg>', caption: "1-12 (-2)⁴ 与 -2⁴ 的区别" },
                        { type: "keypoint", label: "符号规律", text: "① <strong>正数</strong>的任何次幂都是<strong>正数</strong>；<br>② <strong>负数</strong>的奇数次幂是<strong>负数</strong>，偶数次幂是<strong>正数</strong>；<br>③ <strong>$0$</strong>的任何正整数次幂都是<strong>$0$</strong>。" },
                        { type: "tip", label: "记忆口诀", text: "负数的乘方看指数：奇负偶正。指数是奇数→负，指数是偶数→正。" },
                        { type: "example", title: "例题1", question: "计算：$(1)$ $(-3)^2$　$(2)$ $-3^2$　$(3)$ $(-2)^3$　$(4)$ $(-1)^{100}$　$(5)$ $(-1)^{101}$", solution: "$(1)$ $(-3)^2=9$（偶数次幂为正）<br>$(2)$ $-3^2=-9$（底数是3，负号在外）<br>$(3)$ $(-2)^3=-8$（奇数次幂为负）<br>$(4)$ $(-1)^{100}=1$（偶数次幂为正）<br>$(5)$ $(-1)^{101}=-1$（奇数次幂为负）" },
                        { type: "example", title: "例题2", question: "计算 $(-\\frac{1}{2})^4$ 和 $(-\\frac{1}{3})^3$。", solution: "$(-\\frac{1}{2})^4 = (-\\frac{1}{2})\\times(-\\frac{1}{2})\\times(-\\frac{1}{2})\\times(-\\frac{1}{2}) = \\frac{1}{16}$（偶数次幂为正）<br>$(-\\frac{1}{3})^3 = (-\\frac{1}{3})\\times(-\\frac{1}{3})\\times(-\\frac{1}{3}) = -\\frac{1}{27}$（奇数次幂为负）" },
                        { type: "heading", text: "二、科学记数法" },
                        { type: "paragraph", text: "在科学研究和日常生活中，我们经常遇到很大或很小的数。比如地球的质量约为 $5\\,972\\,000\\,000\\,000\\,000\\,000\\,000\\,000$ kg，光速约为 $300\\,000\\,000$ m/s。这些数写起来很麻烦，容易出错。科学家们发明了<strong>科学记数法</strong>来简化表示。" },
                        { type: "keypoint", label: "重点定义", text: "<strong>科学记数法</strong>：把一个大于 $10$ 的数表示成 $a \\times 10^n$ 的形式（$1 \\leq a < 10$，$n$ 为正整数）。$n$ 等于原数整数部分的位数减 $1$。" },
                        { type: "svg", svg: '<svg viewBox="0 0 600 120" xmlns="http://www.w3.org/2000/svg"><rect x="20" y="10" width="560" height="100" rx="10" fill="#E3F2FD" stroke="#5B8DEF" stroke-width="2"/><text x="40" y="45" font-size="16" fill="#333" font-weight="bold">将 56700000 用科学记数法表示：</text><text x="40" y="75" font-size="15" fill="#5B8DEF" font-weight="bold">56700000 → 5.67 × 10⁷</text><text x="40" y="98" font-size="12" fill="#666">8位整数 → n = 8-1 = 7</text><text x="300" y="75" font-size="15" fill="#66BB6A" font-weight="bold">小数点左移7位</text><text x="300" y="98" font-size="12" fill="#666">1 ≤ 5.67 < 10 ✓</text></svg>', caption: "1-13 科学记数法的转换方法" },
                        { type: "example", title: "例题3", question: "用科学记数法表示：$(1)$ $696\\,000$　$(2)$ $-2\\,400\\,000$　$(3)$ $5\\,700\\,000\\,000$", solution: "$(1)$ $696\\,000$ 有6位整数，$n=5$：$6.96 \\times 10^5$<br>$(2)$ $-2\\,400\\,000$ 有7位整数，$n=6$：$-2.4 \\times 10^6$<br>$(3)$ $5\\,700\\,000\\,000$ 有10位整数，$n=9$：$5.7 \\times 10^9$" },
                        { type: "example", title: "例题4", question: "下列用科学记数法表示的数，原数是多少？$(1)$ $3.2 \\times 10^4$　$(2)$ $-1.05 \\times 10^6$", solution: "$(1)$ $3.2 \\times 10^4 = 32000$<br>$(2)$ $-1.05 \\times 10^6 = -1050000$" },
                        { type: "heading", text: "三、近似数" },
                        { type: "paragraph", text: "在实际生活中，很多数据都是近似的。比如你的身高约 $1.65$ 米，操场周长约 $400$ 米。近似数与精确数的区别在于，近似数有一定的误差范围。" },
                        { type: "keypoint", label: "概念", text: "<strong>精确度</strong>：近似数四舍五入到某一位，就说这个近似数精确到那一位。" },
                        { type: "table", headers: ["近似数", "精确到", "说明"], rows: [
                            ["$3.14$", "百分位", "小数点后第二位"],
                            ["$3.1$", "十分位", "小数点后第一位"],
                            ["$3$", "个位", "精确到个位"],
                            ["$5.6 \\times 10^4$", "千位", "$6$在千位上"],
                            ["$2.50 \\times 10^3$", "百位", "$0$在百位上（注意0不能省略）"],
                            ["$3.14 \\times 10^5$", "千位", "$4$在千位上"]
                        ]},
                        { type: "warn", label: "注意", text: "① 科学记数法 $a \\times 10^n$ 的精确度看 $a$ 的最后一位数字在原数中的位置。<br>② $2.50 \\times 10^3$ 和 $2.5 \\times 10^3$ 的精确度不同！前者精确到百位，后者精确到百位...不对，$2.5\\times10^3=2500$精确到百位，$2.50\\times10^3=2500$精确到十位（末尾的0有意义）。" },
                        { type: "example", title: "例题5", question: "按括号内要求取近似值：$(1)$ $0.85149$（精确到千分位）　$(2)$ $32\\,950$（精确到百位）　$(3)$ $3.14159$（精确到 $0.01$）", solution: "$(1)$ 千分位是$1$，后一位$4$舍去，得$0.851$<br>$(2)$ 百位是$9$，后一位$5$进一，得$3.30 \\times 10^4$<br>$(3)$ 精确到$0.01$即百分位，百分位是$4$，后一位$1$舍去，得$3.14$" },
                        { type: "heading", text: "四、知识拓展" },
                        { type: "paragraph", text: "乘方运算在计算机科学中非常重要。计算机中存储数据使用的二进制就是基于 $2$ 的幂。比如 $1$ KB $= 2^{10}$ 字节 $= 1024$ 字节，$1$ MB $= 2^{20}$ 字节 $= 1048576$ 字节。" },
                        { type: "paragraph", text: "科学记数法在物理学中广泛应用。比如阿伏伽德罗常数约为 $6.02 \\times 10^{23}$，普朗克常数约为 $6.63 \\times 10^{-34}$ J·s。没有科学记数法，这些数写起来会非常痛苦！" },
                        { type: "tip", label: "有趣的事实", text: "$(-1)^n$ 的规律：当 $n$ 为偶数时 $(-1)^n = 1$，当 $n$ 为奇数时 $(-1)^n = -1$。这个性质在高中数学中会经常用到，特别是在数列求和和二项式定理中。" }
                    ],
                    exercises: [
                        { type: "choice", question: "计算 $(-2)^3$ 的结果是（　　）", options: ["$-6$", "$6$", "$-8$", "$8$"], answer: "C", explanation: "$(-2)^3=(-2)\\times(-2)\\times(-2)$。$(-2)\\times(-2)=4$，$4\\times(-2)=-8$。负数的奇数次幂为负。" },
                        { type: "choice", question: "用科学记数法表示 $56700000$，正确的是（　　）", options: ["$5.67 \\times 10^6$", "$5.67 \\times 10^7$", "$56.7 \\times 10^6$", "$0.567 \\times 10^8$"], answer: "B", explanation: "$56700000$有8位整数，$n=8-1=7$。科学记数法要求$1 \\leq a < 10$，所以是$5.67 \\times 10^7$。" },
                        { type: "choice", question: "下列各组中，数值相等的是（　　）", options: ["$-2^3$ 和 $(-2)^3$", "$-3^2$ 和 $(-3)^2$", "$2^3$ 和 $3^2$", "$(-2)^2$ 和 $-2^2$"], answer: "C", explanation: "A：$-2^3=-8$，$(-2)^3=-8$相等...等等，A也相等？不，A确实相等（都是-8）。但C：$2^3=8$，$3^2=9$，不相等。让我重新看：A：$-2^3=-(8)=-8$，$(-2)^3=-8$，相等。B：$-3^2=-9$，$(-3)^2=9$，不相等。C：$2^3=8$，$3^2=9$，不相等。D：$(-2)^2=4$，$-2^2=-4$，不相等。所以A和...答案是A？但原答案给了C。让我再验证A：$-2^3$的底数是2，$-2^3=-(2^3)=-8$；$(-2)^3$的底数是-2，$(-2)^3=-8$。确实A也相等。但原答案设为C可能有误。实际正确答案应为A。让我改：A：$-2^3=-8$，$(-2)^3=-8$，相等。C：$2^3=8$，$3^2=9$，不相等。答案应该是A。", answer: "A", explanation: "$-2^3=-(2^3)=-8$，$(-2)^3=(-2)\\times(-2)\\times(-2)=-8$，两者相等。B：$-9\\neq9$；C：$8\\neq9$；D：$4\\neq-4$。" },
                        { type: "fill", question: "近似数 $3.14 \\times 10^5$ 精确到 ____ 位。", answer: "千", explanation: "$3.14 \\times 10^5 = 314000$，其中$4$在千位上，所以精确到千位。" },
                        { type: "fill", question: "计算：$(-1)^{2024} + (-1)^{2025} = $ ____。", answer: "0", explanation: "$2024$是偶数，$(-1)^{2024}=1$；$2025$是奇数，$(-1)^{2025}=-1$。$1+(-1)=0$。" }
                    ]
                }
            ]
        },
        // ===== 第二章 整式的加减 =====
        {
            title: "第二章 整式的加减",
            icon: "✏️",
            color: "#FF8A65",
            lessons: [
                {
                    id: "2-1",
                    title: "2.1 整式",
                    icon: "📝",
                    difficulty: "基础",
                    content: [
                        { type: "heading", text: "一、用字母表示数" },
                        { type: "paragraph", text: "在小学阶段，我们主要学习的是具体的数字运算。但到了初中，数学开始变得\"抽象\"了——我们开始用<strong>字母表示数</strong>。这是数学思维的一次重要飞跃！" },
                        { type: "paragraph", text: "为什么要用字母表示数？因为用字母可以表示<strong>一般规律</strong>。比如，加法交换律用文字描述是\"两个数相加，交换位置，和不变\"，用字母表示就是简洁的 $a+b=b+a$。再比如，苹果每斤 $a$ 元，买 $5$ 斤需要 $5a$ 元；正方形边长为 $a$，则周长为 $4a$，面积为 $a^2$。" },
                        { type: "svg", svg: '<svg viewBox="0 0 600 160" xmlns="http://www.w3.org/2000/svg"><rect x="20" y="10" width="560" height="140" rx="12" fill="#FFF8E1" stroke="#FFCA28" stroke-width="1.5"/><text x="40" y="40" font-size="15" fill="#E65100" font-weight="bold">用字母表示数的常见场景：</text><text x="40" y="70" font-size="13" fill="#333">圆的面积：S = πr²</text><text x="40" y="95" font-size="13" fill="#333">速度公式：s = vt</text><text x="40" y="120" font-size="13" fill="#333">正方体体积：V = a³</text><text x="280" y="70" font-size="13" fill="#333">利润 = 售价 - 成本：L = p - c</text><text x="280" y="95" font-size="13" fill="#333">摄氏度转华氏度：F = 1.8C + 32</text><text x="280" y="120" font-size="13" fill="#333">勾股定理：a² + b² = c²</text></svg>', caption: "2-1 用字母表示数的应用场景" },
                        { type: "tip", label: "书写规则", text: "① 字母与字母相乘，乘号可省略（$a \\times b = ab$）；<br>② 数字与字母相乘，乘号可省略，<strong>数字写前面</strong>（$a \\times 3 = 3a$，不是 $a3$）；<br>③ 除法写成分数形式（$a \\div b = \\frac{a}{b}$）；<br>④ 带分数要化成假分数（$1\\frac{1}{2}a$ 写成 $\\frac{3}{2}a$）；<br>⑤ 数字与字母相乘时，$1$ 可以省略（$1 \\times a = a$）。" },
                        { type: "heading", text: "二、单项式" },
                        { type: "keypoint", label: "重点定义", text: "<strong>单项式</strong>：由数与字母的乘积组成的代数式。单独一个数或字母也是单项式。如 $3x$、$-5a^2b$、$x$、$7$。" },
                        { type: "paragraph", text: "简单来说，单项式就是\"只有乘法没有加减\"的式子。比如 $3x$ 是 $3$ 和 $x$ 的乘积，$-5a^2b$ 是 $-5$、$a^2$ 和 $b$ 的乘积。单独一个数（如 $7$）或一个字母（如 $x$）也算单项式。" },
                        { type: "warn", label: "注意", text: "① 单项式中不含加减运算；<br>② 分母中不能含字母，$\\frac{1}{x}$ 不是单项式（这是分式，在八年级会学到）；<br>③ $\\pi$ 是数不是字母，所以 $\\pi r^2$ 是单项式，系数是 $\\pi$；<br>④ $-x$ 的系数是 $-1$（不是没有系数）。" },
                        { type: "keypoint", label: "系数与次数", text: "<strong>系数</strong>：单项式中的数字因数（包括符号）。<br><strong>次数</strong>：所有字母的指数的和。" },
                        { type: "svg", svg: '<svg viewBox="0 0 600 120" xmlns="http://www.w3.org/2000/svg"><rect x="20" y="10" width="560" height="100" rx="10" fill="#E8F5E9" stroke="#66BB6A" stroke-width="2"/><text x="50" y="55" font-size="28" fill="#5B8DEF" font-weight="bold">-7x²y</text><line x1="70" y1="65" x2="50" y2="85" stroke="#FF8A65" stroke-width="1.5"/><text x="10" y="95" font-size="13" fill="#FF8A65" font-weight="bold">系数=-7</text><line x1="120" y1="40" x2="150" y2="20" stroke="#66BB6A" stroke-width="1.5"/><text x="155" y="18" font-size="13" fill="#66BB6A" font-weight="bold">指数=2</text><line x1="145" y1="65" x2="175" y2="85" stroke="#AB47BC" stroke-width="1.5"/><text x="180" y="95" font-size="13" fill="#AB47BC" font-weight="bold">指数=1(y=y¹)</text><text x="350" y="50" font-size="14" fill="#333">次数 = 2 + 1 = 3</text><text x="350" y="80" font-size="14" fill="#333">系数 = -7</text></svg>', caption: "2-2 单项式的系数和次数" },
                        { type: "example", title: "例题1", question: "指出下列单项式的系数和次数：$(1)$ $-7x^2y$　$(2)$ $\\frac{1}{3}ab^2c^3$　$(3)$ $-a$　$(4)$ $\\frac{2\\pi r}{3}$", solution: "$(1)$ 系数$-7$，次数$2+1=3$<br>$(2)$ 系数$\\frac{1}{3}$，次数$1+2+3=6$<br>$(3)$ 系数$-1$，次数$1$（$-a = -1 \\cdot a^1$）<br>$(4)$ 系数$\\frac{2\\pi}{3}$（$\\pi$是数不是字母），次数$1$" },
                        { type: "example", title: "例题2", question: "若单项式 $-3x^m y^3$ 的次数是 $5$，求 $m$ 的值。", solution: "单项式的次数 $= m + 3 = 5$，所以 $m = 2$。" },
                        { type: "heading", text: "三、多项式" },
                        { type: "keypoint", label: "重点定义", text: "<strong>多项式</strong>：几个单项式的和。每个单项式叫<strong>项</strong>，不含字母的项叫<strong>常数项</strong>。<strong>次数</strong>：最高次项的次数。" },
                        { type: "paragraph", text: "多项式是由几个单项式通过加减法组合而成的。比如 $3x^2 - 5x + 2$ 就是一个多项式，它由三个项组成：$3x^2$、$-5x$、$+2$。其中 $+2$ 是常数项。" },
                        { type: "warn", label: "注意", text: "① 多项式的每一项都<strong>包括它前面的符号</strong>！如 $3x^2 - 5x + 2$ 的项是 $3x^2$、$-5x$、$+2$，不是 $3x^2$、$5x$、$2$。<br>② 多项式的次数是<strong>最高次项</strong>的次数，不是所有项次数的和。" },
                        { type: "example", title: "例题3", question: "指出多项式 $3x^2y - 5xy^2 + 7x - 8$ 的项、常数项和次数。", solution: "四项：$3x^2y$、$-5xy^2$、$7x$、$-8$。<br>常数项：$-8$。<br>$3x^2y$ 次数为 $2+1=3$；$-5xy^2$ 次数为 $1+2=3$；$7x$ 次数为 $1$；$-8$ 次数为 $0$。<br>最高次为 $3$，是<strong>三次四项式</strong>。" },
                        { type: "example", title: "例题4", question: "已知多项式 $2x^3 - 3x^2y^n + 5x - 7$ 是四次四项式，求 $n$ 的值。", solution: "要使多项式为四次，则 $-3x^2y^n$ 的次数为 $4$，即 $2 + n = 4$，所以 $n = 2$。" },
                        { type: "heading", text: "四、整式" },
                        { type: "keypoint", label: "定义", text: "<strong>整式</strong>：单项式与多项式统称为整式。" },
                        { type: "svg", svg: '<svg viewBox="0 0 500 180" xmlns="http://www.w3.org/2000/svg"><rect x="170" y="10" width="160" height="40" rx="8" fill="#5B8DEF"/><text x="250" y="36" text-anchor="middle" font-size="18" fill="#fff" font-weight="bold">整式</text><line x1="250" y1="50" x2="150" y2="90" stroke="#999" stroke-width="1.5"/><line x1="250" y1="50" x2="350" y2="90" stroke="#999" stroke-width="1.5"/><rect x="90" y="90" width="120" height="36" rx="8" fill="#FF8A65"/><text x="150" y="113" text-anchor="middle" font-size="16" fill="#fff" font-weight="bold">单项式</text><rect x="290" y="90" width="120" height="36" rx="8" fill="#66BB6A"/><text x="350" y="113" text-anchor="middle" font-size="16" fill="#fff" font-weight="bold">多项式</text><text x="150" y="150" text-anchor="middle" font-size="13" fill="#666">如: 3x, -5a²b, 7, x</text><text x="350" y="150" text-anchor="middle" font-size="13" fill="#666">如: 2x²-3x+1, x-y+2</text></svg>', caption: "2-3 整式的分类" },
                        { type: "heading", text: "五、知识拓展" },
                        { type: "paragraph", text: "整式是代数学的基础。在初中阶段，我们主要学习整式的加减、乘除和因式分解。到了高中，还会学习分式、根式等更复杂的代数式。整式的学习为后续学习方程、函数等核心内容打下了基础。" },
                        { type: "paragraph", text: "在计算机编程中，多项式也有着重要的应用。比如，计算机图形学中的贝塞尔曲线就是用多项式来描述的；密码学中的 RSA 加密算法也依赖于大整数的多项式运算。" },
                        { type: "tip", label: "学习建议", text: "学习整式时要注意：① 区分单项式和多项式；② 正确找出系数（包括符号）；③ 正确计算次数（单项式是所有字母指数的和，多项式是最高次项的次数）；④ 书写要规范，数字在前字母在后。" }
                    ],
                    exercises: [
                        { type: "choice", question: "下列说法正确的是（　　）", options: ["$\\frac{x}{3}$ 是单项式，系数是 $\\frac{1}{3}$", "$\\frac{3}{x}$ 是单项式", "$x^2+1$ 是二次一项式", "$-5$ 不是单项式"], answer: "A", explanation: "$\\frac{x}{3}=\\frac{1}{3}x$是单项式（A正确）；$\\frac{3}{x}$分母含字母不是单项式（B错误）；$x^2+1$是二次二项式（C错误）；单独一个数$-5$也是单项式（D错误）。" },
                        { type: "choice", question: "多项式 $2x^3y^2 - 3x^2y + 5x - 7$ 的次数和常数项分别是（　　）", options: ["次数$5$，常数项$7$", "次数$5$，常数项$-7$", "次数$3$，常数项$-7$", "次数$4$，常数项$7$"], answer: "B", explanation: "$2x^3y^2$次数是$3+2=5$，最高次为$5$。常数项是不含字母的项$-7$。" },
                        { type: "choice", question: "下列各式中，不是整式的是（　　）", options: ["$3x - 5$", "$\\frac{x+1}{2}$", "$\\frac{2}{x+1}$", "$-7$"], answer: "C", explanation: "整式包括单项式和多项式。$3x-5$是多项式；$\\frac{x+1}{2}=\\frac{1}{2}x+\\frac{1}{2}$是多项式；$-7$是单项式。$\\frac{2}{x+1}$分母含字母，不是整式（是分式）。" },
                        { type: "fill", question: "单项式 $-\\frac{2}{3}a^3b^2c$ 的系数是 ____ ，次数是 ____。", answer: "-2/3,6", explanation: "系数是$-\\frac{2}{3}$。次数是$3+2+1=6$。" },
                        { type: "fill", question: "若单项式 $2x^2y^n$ 的次数是 $5$，则 $n = $ ____。", answer: "3", explanation: "次数 $= 2 + n = 5$，所以 $n = 3$。" }
                    ]
                },
                {
                    id: "2-2",
                    title: "2.2 整式的加减",
                    icon: "🔀",
                    difficulty: "重点",
                    content: [
                        { type: "heading", text: "一、同类项" },
                        { type: "paragraph", text: "在超市里，我们会把水果分类摆放——苹果和苹果放一起，香蕉和香蕉放一起。在数学中，我们也需要把类似的式子\"分类\"，这样才能进行合并化简。这就是<strong>同类项</strong>的概念。" },
                        { type: "keypoint", label: "重点定义", text: "<strong>同类项</strong>：所含字母相同，并且相同字母的指数也相同的项。几个常数项也是同类项。" },
                        { type: "tip", label: "判断方法", text: "<strong>两看两不看</strong>：<br>两看：① <strong>看字母</strong>——完全相同；② <strong>看指数</strong>——相同字母的指数分别相同。<br>两不看：① <strong>不看系数</strong>——系数可以不同；② <strong>不看字母顺序</strong>——$x^2y$ 和 $yx^2$ 是同类项。" },
                        { type: "svg", svg: '<svg viewBox="0 0 600 180" xmlns="http://www.w3.org/2000/svg"><rect x="20" y="10" width="270" height="75" rx="10" fill="#E8F5E9" stroke="#66BB6A" stroke-width="2"/><text x="155" y="35" text-anchor="middle" font-size="15" fill="#2E7D32" font-weight="bold">✓ 是同类项</text><text x="155" y="60" text-anchor="middle" font-size="14" fill="#333">3x²y 和 -5yx²</text><text x="155" y="78" text-anchor="middle" font-size="11" fill="#666">字母相同，指数相同</text><rect x="310" y="10" width="270" height="75" rx="10" fill="#FFEBEE" stroke="#FF6B6B" stroke-width="2"/><text x="445" y="35" text-anchor="middle" font-size="15" fill="#C62828" font-weight="bold">✗ 不是同类项</text><text x="445" y="60" text-anchor="middle" font-size="14" fill="#333">2a²b 和 2ab²</text><text x="445" y="78" text-anchor="middle" font-size="11" fill="#666">a的指数不同，b的指数不同</text><rect x="20" y="100" width="270" height="75" rx="10" fill="#E8F5E9" stroke="#66BB6A" stroke-width="2"/><text x="155" y="125" text-anchor="middle" font-size="15" fill="#2E7D32" font-weight="bold">✓ 是同类项</text><text x="155" y="150" text-anchor="middle" font-size="14" fill="#333">4 和 -7</text><text x="155" y="168" text-anchor="middle" font-size="11" fill="#666">常数项都是同类项</text><rect x="310" y="100" width="270" height="75" rx="10" fill="#FFEBEE" stroke="#FF6B6B" stroke-width="2"/><text x="445" y="125" text-anchor="middle" font-size="15" fill="#C62828" font-weight="bold">✗ 不是同类项</text><text x="445" y="150" text-anchor="middle" font-size="14" fill="#333">3xy 和 3xz</text><text x="445" y="168" text-anchor="middle" font-size="11" fill="#666">字母不同(y≠z)</text></svg>', caption: "2-4 同类项的判断" },
                        { type: "example", title: "例题1", question: "判断下列各组是否为同类项：<br>$(1)$ $3x^2y$ 与 $-5yx^2$　$(2)$ $2a^2b$ 与 $2ab^2$　$(3)$ $4$ 与 $-7$　$(4)$ $-3mn$ 与 $5nm$", solution: "$(1)$ 是（字母相同，$x$指数都是$2$，$y$指数都是$1$，字母顺序不同没关系）<br>$(2)$ 不是（$a$的指数不同：$2\\neq1$；$b$的指数也不同：$1\\neq2$）<br>$(3)$ 是（常数项都是同类项）<br>$(4)$ 是（字母相同，指数相同，$mn$和$nm$是同样的字母）" },
                        { type: "example", title: "例题2", question: "若 $-2x^m y^3$ 与 $3x^2 y^n$ 是同类项，求 $m$ 和 $n$ 的值。", solution: "因为是同类项，所以相同字母的指数相同：<br>$x$ 的指数：$m = 2$<br>$y$ 的指数：$n = 3$" },
                        { type: "heading", text: "二、合并同类项" },
                        { type: "keypoint", label: "重点法则", text: "<strong>合并同类项</strong>：把同类项的系数相加，字母和字母的指数保持不变。" },
                        { type: "paragraph", text: "合并同类项的口诀：<strong>系数相加减，字母和指数不变</strong>。就像 $3$ 个苹果加 $5$ 个苹果等于 $8$ 个苹果一样，$3x + 5x = 8x$。" },
                        { type: "svg", svg: '<svg viewBox="0 0 600 80" xmlns="http://www.w3.org/2000/svg"><rect x="10" y="15" width="580" height="55" rx="10" fill="#FFF8E1" stroke="#FFCA28" stroke-width="1.5"/><text x="30" y="48" font-size="17" fill="#E65100">3x²y</text><text x="100" y="48" font-size="18" fill="#333">+</text><text x="130" y="48" font-size="17" fill="#E65100">5x²y</text><text x="210" y="48" font-size="18" fill="#333">=</text><text x="250" y="48" font-size="17" fill="#2E7D32" font-weight="bold">(3+5)x²y</text><text x="400" y="48" font-size="18" fill="#333">=</text><text x="440" y="48" font-size="17" fill="#1565C0" font-weight="bold">8x²y</text><text x="30" y="68" font-size="11" fill="#FF8A65">系数相加: 3+5=8</text><text x="250" y="68" font-size="11" fill="#66BB6A">字母不变: x²y</text></svg>', caption: "2-5 合并同类项的过程" },
                        { type: "example", title: "例题3", question: "合并同类项：$4a^2b - 3ab^2 + 2a^2b + 5ab^2 - a^2b$", solution: "找同类项：$4a^2b$、$2a^2b$、$-a^2b$ 是同类项；$-3ab^2$、$5ab^2$ 是同类项。<br>合并：$(4+2-1)a^2b + (-3+5)ab^2 = 5a^2b + 2ab^2$" },
                        { type: "example", title: "例题4", question: "合并同类项：$3(x+y)^2 - 2(x+y)^2 + 5(x+y)^2 - (x+y)^2$<br>（提示：把 $x+y$ 看作一个整体）", solution: "把 $(x+y)^2$ 看作一个整体，这些项是同类项。<br>$(3-2+5-1)(x+y)^2 = 5(x+y)^2$" },
                        { type: "heading", text: "三、去括号法则" },
                        { type: "paragraph", text: "在化简整式时，经常需要处理括号。<strong>去括号</strong>是整式加减的关键步骤，也是容易出错的地方。" },
                        { type: "keypoint", label: "重点法则", text: "① 括号前是\"$+$\"号，去掉括号后各项<strong>不变号</strong>：$a+(b-c)=a+b-c$<br>② 括号前是\"$-$\"号，去掉括号后各项<strong>都变号</strong>（正变负，负变正）：$a-(b-c)=a-b+c$" },
                        { type: "svg", svg: '<svg viewBox="0 0 600 140" xmlns="http://www.w3.org/2000/svg"><rect x="20" y="10" width="270" height="55" rx="10" fill="#E8F5E9" stroke="#66BB6A" stroke-width="2"/><text x="155" y="45" text-anchor="middle" font-size="15" fill="#2E7D32" font-weight="bold">a + (b - c) = a + b - c</text><text x="155" y="62" text-anchor="middle" font-size="12" fill="#666">括号前是+，各项不变号 ✓</text><rect x="310" y="10" width="270" height="55" rx="10" fill="#FFEBEE" stroke="#FF6B6B" stroke-width="2"/><text x="445" y="45" text-anchor="middle" font-size="15" fill="#C62828" font-weight="bold">a - (b - c) = a - b + c</text><text x="445" y="62" text-anchor="middle" font-size="12" fill="#666">括号前是-，各项都变号 ✓</text><rect x="20" y="80" width="560" height="50" rx="10" fill="#FFF3E0" stroke="#FF9800" stroke-width="1.5"/><text x="300" y="110" text-anchor="middle" font-size="14" fill="#E65100" font-weight="bold">注意：括号前是"-"号时，括号内每一项都要变号！</text></svg>', caption: "2-6 去括号法则" },
                        { type: "warn", label: "易错点", text: "括号前是\"$-$\"号时，括号内<strong>每一项</strong>都要变号，不能漏掉！<br>常见错误：$-(2a-3b+c) = -2a-3b+c$ ❌（$-3b$ 应该变 $+3b$，$+c$ 应该变 $-c$）<br>正确：$-(2a-3b+c) = -2a+3b-c$ ✓" },
                        { type: "example", title: "例题5", question: "去括号：$(1)$ $x+(2y-3z)$　$(2)$ $a-(2b-3c+d)$　$(3)$ $-(3x^2-2x+1)$", solution: "$(1)$ $x+2y-3z$（括号前是$+$，不变号）<br>$(2)$ $a-2b+3c-d$（括号前是$-$，每项变号：$+2b→-2b$，$-3c→+3c$，$+d→-d$）<br>$(3)$ $-3x^2+2x-1$（括号前是$-$，每项变号）" },
                        { type: "example", title: "例题6", question: "去括号：$2x-3(y-2z)-(x-3y+4z)$", solution: "第一个括号前是$-$（省略了乘号），先算乘法：$2x-3y+6z$<br>第二个括号前是$-$：$-x+3y-4z$<br>合并：$(2x-x)+(-3y+3y)+(6z-4z) = x+2z$" },
                        { type: "heading", text: "四、整式的加减" },
                        { type: "keypoint", label: "步骤", text: "整式加减运算的一般步骤：<br>① 如果有括号，先<strong>去括号</strong>（注意符号变化）<br>② 再<strong>合并同类项</strong>" },
                        { type: "example", title: "例题7", question: "化简：$(3x^2-2x+1)-(x^2-3x-2)$", solution: "去括号：$3x^2-2x+1-x^2+3x+2$<br>合并同类项：$(3-1)x^2+(-2+3)x+(1+2) = 2x^2+x+3$" },
                        { type: "example", title: "例题8", question: "化简求值：$3(2a^2-3ab)-2(3a^2-ab)$，其中 $a=2$，$b=-1$。", solution: "去括号：$6a^2-9ab-6a^2+2ab$<br>合并：$-7ab$<br>代入：$-7\\times2\\times(-1) = 14$" },
                        { type: "tip", label: "化简求值的技巧", text: "遇到\"化简求值\"题，一定要先化简再代入数值。如果直接代入，计算量会大很多，而且容易出错。化简后式子变简单了，计算就方便了。" },
                        { type: "example", title: "例题9", question: "已知 $A = 2x^2 - 3x + 1$，$B = x^2 + 2x - 5$，求 $A - B$。", solution: "$A - B = (2x^2 - 3x + 1) - (x^2 + 2x - 5)$<br>去括号：$2x^2 - 3x + 1 - x^2 - 2x + 5$<br>合并：$x^2 - 5x + 6$" },
                        { type: "heading", text: "五、知识拓展" },
                        { type: "paragraph", text: "整式的加减是代数运算的基础，在后续学习中非常重要。解方程、解不等式、求函数值等都需要用到整式的加减。在高中数学中，还会学习整式的乘法、除法、因式分解等更复杂的运算。" },
                        { type: "paragraph", text: "有趣的是，整式的加减在计算机代数系统（如 Mathematica、Maple）中有广泛应用。这些软件能够自动进行多项式的化简和运算，背后使用的就是我们这里学到的基本原理——去括号和合并同类项。" },
                        { type: "tip", label: "总结", text: "整式加减的核心就两步：<strong>去括号</strong> + <strong>合并同类项</strong>。记住：① 去括号时看括号前的符号（正不变负全变）；② 合并同类项时只算系数，字母和指数不变。多做练习，熟能生巧！" }
                    ],
                    exercises: [
                        { type: "choice", question: "下列各组中，不是同类项的是（　　）", options: ["$-3$ 和 $0$", "$2x^2y$ 和 $-3yx^2$", "$5a^2b$ 和 $5ab^2$", "$\\frac{1}{2}m^2n$ 和 $3nm^2$"], answer: "C", explanation: "$5a^2b$中$a$指数是$2$，$b$指数是$1$；$5ab^2$中$a$指数是$1$，$b$指数是$2$。相同字母的指数不同，不是同类项。" },
                        { type: "choice", question: "化简 $-(2a-3b+c)$ 的结果是（　　）", options: ["$-2a-3b+c$", "$-2a+3b-c$", "$2a-3b+c$", "$2a+3b-c$"], answer: "B", explanation: "括号前是\"$-$\"号，每一项变号：$+2a→-2a$，$-3b→+3b$，$+c→-c$。结果为$-2a+3b-c$。" },
                        { type: "choice", question: "若 $3x^m y^2$ 与 $-2x^3 y^n$ 是同类项，则 $m+n = $（　　）", options: ["$3$", "$5$", "$6$", "$7$"], answer: "B", explanation: "同类项要求相同字母的指数相同，所以$m=3$，$n=2$，$m+n=5$。" },
                        { type: "fill", question: "化简：$(2x^2-3x+5)+(x^2+2x-3)-(3x^2-x-2) = $ ____", answer: "4", explanation: "去括号：$2x^2-3x+5+x^2+2x-3-3x^2+x+2$。合并：$(2+1-3)x^2+(-3+2+1)x+(5-3+2)=0+0+4=4$。" },
                        { type: "fill", question: "化简求值：$2(x^2-xy)-3(x^2-2xy)$，其中 $x=-1$，$y=2$，则原式 $=$ ____。", answer: "14", explanation: "去括号：$2x^2-2xy-3x^2+6xy=-x^2+4xy$。代入$x=-1,y=2$：$-1+4(-1)(2)=-1-8=-9$。不对，让我重算：$-(-1)^2+4(-1)(2)=-1-8=-9$。但答案给的是14...让我重新化简：$2x^2-2xy-3x^2+6xy=(-1)x^2+4xy=-x^2+4xy$。代入：$-1+4\\times(-1)\\times2=-1-8=-9$。答案应该是-9。", answer: "-9", explanation: "去括号：$2x^2-2xy-3x^2+6xy=-x^2+4xy$。代入$x=-1,y=2$：$-(-1)^2+4\\times(-1)\\times2=-1-8=-9$。" }
                    ]
                }
            ]
        }
    ]
};
